---
- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: yes

- name: Update all packages to the latest version
  apt:
    upgrade: dist

- name: Remove useless packages from the cache
  apt:
    autoclean: yes

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes

- name: Install a list of packages
  apt:
    pkg:
    - ufw
    - git
    - smartmontools
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common
    - python3
    - python3-pip
    - python-pip
    - python-setuptools

- name: Reject everything and enable UFW
  ufw:
    state: enabled
    logging: 'on'
    policy: reject

- name: Allow port 22
  ufw:
    rule: allow
    name: OpenSSH

- name: Install docker repo (Debian)
  apt_repository:
    repo: "deb https://download.docker.com/linux/{{ ansible_facts['distribution']|lower }} {{ ansible_facts['distribution_release'] }} stable"
    state: present
  tags: docker

- name: Install docker ce (Debian)
  apt:
    state: present
    pkg:
      - "docker-ce={{ debian_docker_version }}~3-0~{{ ansible_facts['distribution']|lower }}-{{ ansible_facts['distribution_release']|lower }}"
      - "docker-ce-cli={{ debian_docker_version }}~3-0~{{ ansible_facts['distribution']|lower }}-{{ ansible_facts['distribution_release']|lower }}"
      - "containerd.io"
  tags: docker
