---
# tasks file for baseline

- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: yes
  when: ansible_facts['os_family'] == "Debian"

- name: Update all packages to the latest version
  apt:
    upgrade: dist
  when: ansible_facts['os_family'] == "Debian"

- name: Remove useless packages from the cache
  apt:
    autoclean: yes
  when: ansible_facts['os_family'] == "Debian"

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes
  when: ansible_facts['os_family'] == "Debian"

- name: Install a list of packages
  apt:
    pkg:
    - ufw
    - git
    - smartmontools
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common
    - python3
  when: ansible_facts['os_family'] == "Debian"

- name: Reject everything and enable UFW
  ufw:
    state: enabled
    logging: 'on'
    policy: reject
  when: ansible_facts['os_family'] == "Debian"

- name: Allow port 22
  ufw:
    rule: allow
    name: OpenSSH
  when: ansible_facts['os_family'] == "Debian"

- name: Update and patch all existing packages (RedHat)
  yum:
    state: latest
    name: "*"
  when: ansible_facts['os_family'] == "RedHat"

- name: Install baseline packages (RedHat)
  yum:
    state: latest
    name: ['rsync','smartmontools','yum-utils','git','python3']
  when: ansible_facts['os_family'] == "RedHat"

- name: Enable and start smartD
  systemd:
    name: smartd
    state: started
    enabled: yes

- name: Install docker repo (RedHat)
  shell: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  tags: docker
  when: ansible_facts['os_family'] == "RedHat"

- name: Install docker repo (Debian)
  shell: "add-apt-repository \"deb [arch=amd64] https://download.docker.com/linux/{{ ansible_facts['distribution']|lower }} $(lsb_release -cs) stable\""
  tags: docker
  when: ansible_facts['os_family'] == "Debian"

- name: Install docker ce (RedHat)
  yum:
    state: present
    name: "{{ rhel_docker_version }}"
  tags: docker
  when: ansible_facts['os_family'] == "RedHat"

- name: Install docker ce (Debian)
  apt:
    state: present
    pkg:
      - "docker-ce={{ debian_docker_version }}~3-0~{{ ansible_facts['distribution']|lower }}-{{ ansible_facts['distribution_release']|lower }}"
      - "docker-ce-cli={{ debian_docker_version }}~3-0~{{ ansible_facts['distribution']|lower }}-{{ ansible_facts['distribution_release']|lower }}"
      - "containerd.io"
  tags: docker
  when: ansible_facts['os_family'] == "Debian"

- name: Enable and start docker
  systemd:
    name: docker
    state: started
    enabled: yes
  tags: docker
