---
# tasks file for baseline
- name: Include OS specific tasks
  include: "{{ ansible_facts['os_family'] | lower }}.yml"

- name: Enable and start docker
  systemd:
    name: docker
    state: started
    enabled: yes
  tags: docker

- name: Install docker python package
  pip:
    name: ['docker']
