---
- name: Update and patch all existing packages (RedHat)
  yum:
    state: latest
    name: "*"

- name: Enable epel repo (RedHat)
  yum:
    state: latest
    name: ['epel-release']

- name: Install baseline packages (RedHat)
  yum:
    state: latest
    name: ['rsync','smartmontools','yum-utils','git','python3','python3-pip','python-setuptools','python-pip']

- name: Enable and start smartD
  systemd:
    name: smartd
    state: started
    enabled: yes

- name: Install docker repo (RedHat)
  shell: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  tags: docker

- name: Install docker ce (RedHat)
  yum:
    state: present
    name: "{{ rhel_docker_version }}"
  tags: docker
