---
# tasks file for nginx
- name: Install nginx
  apt:
    name: nginx
    state: present
    update_cache: yes
  tags:
    - nginx

- name: Create /etc/nginx/ssl directory
  file:
    path: /etc/nginx/ssl
    state: directory
    mode: '0755'
  tags:
    - nginx

- name: Create dhparam
  get_url:
    url: https://ssl-config.mozilla.org/ffdhe2048.txt
    dest: /etc/nginx/ssl/dhparam.pem
    mode: '0755'
  notify: Restart Nginx
  tags:
    - nginx

- name: Setup domain nginx config
  template:
    src: ../templates/domain.j2
    dest: "/etc/nginx/sites-available/{{ domain_name }}"
    mode: '0644'
  tags:
    - nginx

- name: Create symbolic link to /etc/nginx/sites-enabled/
  file:
    src: "/etc/nginx/sites-available/{{ domain_name }}"
    dest: "/etc/nginx/sites-enabled/{{ domain_name }}"
    state: link
  notify: Restart Nginx
  tags:
    - nginx

- name: Restart Nginx
  service:
    name: nginx
    state: restarted
  tags:
    - nginx

- name: Allow HTTP
  ufw:
    rule: allow
    proto: tcp
    port: '80'
  tags:
    - nginx

- name: Allow HTTPS
  ufw:
    rule: allow
    proto: tcp
    port: '443'
  tags:
    - nginx
