---
- hosts: unifi
  remote_user: ansible
  become: yes
  gather_facts: no
  vars:
    acme_challenge_type: dns-01
    acme_directory: https://acme-v02.api.letsencrypt.org/directory
    acme_version: 2
    acme_email: "{{ lookup('env','ACME_EMAIL') }}"
    letsencrypt_dir: /etc/letsencrypt
    letsencrypt_keys_dir: /etc/letsencrypt/keys
    letsencrypt_csrs_dir: /etc/letsencrypt/csrs
    letsencrypt_certs_dir: /etc/letsencrypt/certs
    letsencrypt_account_key: /etc/letsencrypt/account/account.key
    cloudflare_email: "{{ lookup('env','CLOUDFLARE_EMAIL') }}"
    cloudflare_token: "{{ lookup('env','CLOUDFLARE_TOKEN') }}"
    domain_name: "{{ lookup('env','DOMAIN_NAME') }}"
  roles:
    - baseline
    - unifi
    - letsencrypt
    - nginx
