---
# tasks file for monitoring

- name: Create prometheus user
  user:
    name: "{{ prometheus_user }}"
    state: present
    shell: /sbin/nologin
    system: yes

- name: Download Node Exporter
  get_url:
    url: "https://github.com/prometheus/node_exporter/releases/download/v{{ prometheus_node_exporter_version }}/node_exporter-{{ prometheus_node_exporter_version }}.linux-amd64.tar.gz"
    dest: /tmp/node_exporter-{{ prometheus_node_exporter_version }}.linux-amd64.tar.gz

- name: Setup Prometheus and node_exporter directory
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "/home/{{ prometheus_user }}/{{ prometheus_folder }}/{{ prometheus_node_exporter_folder }}"
    - "/home/{{ prometheus_user }}/{{ prometheus_folder }}/{{ prometheus_node_exporter_textfile_folder }}"
    - "/home/{{ prometheus_user }}/{{ prometheus_folder }}/{{ prometheus_node_exporter_scripts_folder }}"

- name: git clone textfile collector scripts
  ansible.builtin.git:
    repo: "https://github.com/prometheus-community/node-exporter-textfile-collector-scripts.git"
    dest: "/home/{{ prometheus_user }}/{{ prometheus_folder }}/{{ prometheus_node_exporter_scripts_folder }}/"
    accept_hostkey: yes
    force: yes

- name: setup cron for smartmon.sh
  ansible.builtin.cron:
    minute: "*/5"
    state: present
    name: "Node Exporter Collector script for Smart Monitoring Bash Script"
    job: "/home/{{ prometheus_user }}/{{ prometheus_folder }}/{{ prometheus_node_exporter_scripts_folder }}/smartmon.sh > /home/{{ prometheus_user }}/{{ prometheus_folder }}/{{ prometheus_node_exporter_textfile_folder }}/smartmon.prom.$$ && mv /home/{{ prometheus_user }}/{{ prometheus_folder }}/{{ prometheus_node_exporter_textfile_folder }}/smartmon.prom.$$ /home/{{ prometheus_user }}/{{ prometheus_folder }}/{{ prometheus_node_exporter_textfile_folder }}/smartmon.prom"

- name: setup cron for smartmon.py
  ansible.builtin.cron:
    minute: "*/5"
    state: present
    name: "Node Exporter Collector script for Smart Monitoring Python Script"
    job: "/usr/bin/python3 /home/{{ prometheus_user }}/{{ prometheus_folder }}/{{ prometheus_node_exporter_scripts_folder }}/smartmon.py > /home/{{ prometheus_user }}/{{ prometheus_folder }}/{{ prometheus_node_exporter_textfile_folder }}/smartmon-python.prom.$$ && mv /home/{{ prometheus_user }}/{{ prometheus_folder }}/{{ prometheus_node_exporter_textfile_folder }}/smartmon-python.prom.$$ /home/{{ prometheus_user }}/{{ prometheus_folder }}/{{ prometheus_node_exporter_textfile_folder }}/smartmon-python.prom"

- name: Extract tar.gz
  unarchive:
    src: "/tmp/node_exporter-{{ prometheus_node_exporter_version }}.linux-amd64.tar.gz"
    remote_src: yes
    dest: "/home/{{ prometheus_user }}/{{ prometheus_folder }}/{{ prometheus_node_exporter_folder }}"
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_user }}"

- name: symlink node_exporter to a specific version
  file:
    path: "/home/{{ prometheus_user }}/{{ prometheus_folder }}/{{ prometheus_node_exporter_folder }}/node_exporter"
    src: "/home/{{ prometheus_user }}/{{ prometheus_folder }}/{{ prometheus_node_exporter_folder }}/node_exporter-1.0.1.linux-amd64/node_exporter"
    state: link
  notify:
    - restart node_exporter

- name: Create node exporter service
  template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
    mode: 600
  notify:
    - reload daemon
    - restart node_exporter

- name: Start and enable node_exporter service
  systemd:
    name: node_exporter.service
    enabled: yes
    state: started

- name: Include OS specific tasks
  include: "{{ ansible_facts['os_family'] | lower }}.yml"
